/**
 * Narrowing the catalogue by price.
 *
 * The bands are DERIVED FROM THE CATALOGUE rather than hard-coded. A fixed
 * ladder like "under $500 / $500–1,000 / over $1,000" is wrong the moment the
 * shop's prices move, and it produces empty bands that a buyer clicks and
 * bounces off. Reading the real prices means every band on screen has something
 * in it.
 *
 * DEPENDENCY-FREE: the shop page, the URL parser and the tests all read one
 * definition, and nothing here needs a database.
 */

/** An inclusive range in CENTS. `null` on either side means unbounded. */
export type PriceRange = { min: number | null; max: number | null };

export const NO_RANGE: PriceRange = { min: null, max: null };

/** A band offered in the sidebar. */
export type PriceBand = {
  /** Query value, e.g. "0-50000" or "200000-". */
  key: string;
  label: string;
  min: number | null;
  max: number | null;
  /** How many products fall in it — a band with none is never shown. */
  count: number;
};

/** True when nothing is being filtered. */
export function isUnbounded(range: PriceRange): boolean {
  return range.min === null && range.max === null;
}

/**
 * Dollars (as typed by a person) to cents.
 *
 * Accepts "1,299", "$1299", " 1299.50 ". Rejects anything else by returning
 * null, because a filter that silently interprets garbage as 0 shows an empty
 * shop and looks broken.
 */
export function dollarsToCents(value: unknown): number | null {
  if (value === null || value === undefined) return null;
  const cleaned = String(value).replace(/[$,\s]/g, "");
  if (cleaned === "" || !/^\d+(\.\d{1,2})?$/.test(cleaned)) return null;
  const cents = Math.round(Number(cleaned) * 100);
  if (!Number.isFinite(cents) || cents < 0) return null;
  // A price nobody will ever charge. Bounded so a pasted essay can't become a
  // number the database has to compare against.
  return Math.min(cents, 100_000_000);
}

/**
 * Parse the URL's price parameters.
 *
 * Two forms, because both are useful: `?price=50000-200000` is what the band
 * links produce (one parameter, one click), and `?min=500&max=2000` is what the
 * custom form posts (dollars, as typed). The band form wins when both appear.
 *
 * A reversed range is SWAPPED rather than rejected: somebody who types 2000 in
 * the "from" box and 500 in the "to" box means the range between them, and
 * showing them an empty shop for it would be pedantry.
 */
export function parsePriceRange(params: {
  price?: string;
  min?: string;
  max?: string;
}): PriceRange {
  let min: number | null = null;
  let max: number | null = null;

  const band = String(params.price ?? "").trim();
  if (band) {
    const [lo, hi] = band.split("-", 2);
    // Cents here, not dollars: these values are generated by priceBands(), not
    // typed by a person.
    min = /^\d+$/.test(lo ?? "") ? Number(lo) : null;
    max = /^\d+$/.test(hi ?? "") ? Number(hi) : null;
  } else {
    min = dollarsToCents(params.min);
    max = dollarsToCents(params.max);
  }

  if (min !== null && max !== null && min > max) [min, max] = [max, min];
  // A floor of zero is no floor. Normalising it means describeRange() says
  // "Under $1,000" rather than the clumsier "$0 – $1,000", and the band links
  // round-trip to exactly the range they came from.
  if (min === 0) min = null;
  return { min, max };
}

/** Does this price fall in the range? Inclusive at both ends. */
export function matchesRange(priceCents: number, range: PriceRange): boolean {
  if (!Number.isFinite(priceCents)) return false;
  if (range.min !== null && priceCents < range.min) return false;
  if (range.max !== null && priceCents > range.max) return false;
  return true;
}

/** The query value for a range, or undefined when it isn't filtering. */
export function rangeKey(range: PriceRange): string | undefined {
  if (isUnbounded(range)) return undefined;
  return `${range.min ?? 0}-${range.max ?? ""}`;
}

/** 1, 2, 2.5 or 5 × a power of ten — the step sizes that read as deliberate. */
function niceStep(rough: number): number {
  if (rough <= 0) return 1;
  const magnitude = 10 ** Math.floor(Math.log10(rough));
  for (const multiple of [1, 2, 2.5, 5, 10]) {
    if (rough <= magnitude * multiple) return magnitude * multiple;
  }
  return magnitude * 10;
}

/**
 * Build the bands for a set of prices.
 *
 * Returns [] when banding would be meaningless — fewer than three products, or
 * every product the same price. A single band covering everything is a control
 * that does nothing, and it is better not to draw it.
 *
 * The first band is open below and the last open above, so no product can fall
 * outside the ladder because of a rounding boundary.
 */
export function priceBands(pricesCents: number[], target = 4): PriceBand[] {
  const prices = pricesCents.filter((p) => Number.isFinite(p) && p >= 0);
  if (prices.length < 3) return [];

  const lo = Math.min(...prices);
  const hi = Math.max(...prices);
  if (hi === lo) return [];

  const step = niceStep((hi - lo) / target);
  // Start at the round number at or below the cheapest product.
  const start = Math.floor(lo / step) * step;

  const edges: number[] = [];
  for (let edge = start + step; edge <= hi && edges.length < 12; edge += step) {
    edges.push(edge);
  }
  // Everything within one step: nothing to divide.
  if (edges.length === 0) return [];

  const bands: PriceBand[] = [];
  let previous: number | null = null;
  for (const edge of edges) {
    // The stored max is one cent BELOW the boundary while the label shows the
    // round number. matchesRange is inclusive at both ends, so without this a
    // product priced at exactly $1,000 would appear under both "Under $1,000"
    // and "$1,000 – $2,000", and the counts would not add up to the catalogue.
    const max = edge - 1;
    const min = previous;
    bands.push({
      key: `${min ?? 0}-${max}`,
      label: min === null ? `Under ${money(edge)}` : `${money(min)} – ${money(edge)}`,
      min,
      max,
      count: prices.filter((p) => p >= (min ?? 0) && p <= max).length,
    });
    previous = edge;
  }
  // The open-ended top, so the most expensive product is always reachable.
  bands.push({
    key: `${previous}-`,
    label: `${money(previous!)} & up`,
    min: previous,
    max: null,
    count: prices.filter((p) => p >= previous!).length,
  });

  // A band nobody can click into is a dead end. Drop them, and drop the whole
  // ladder if that leaves only one.
  const live = bands.filter((b) => b.count > 0);
  return live.length > 1 ? live : [];
}

/** Whole dollars — bands are round numbers by construction, so cents are noise. */
function money(cents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(cents / 100);
}

/** "Under $1,000" / "$500 – $1,000" / "$2,000 & up" for the active range. */
export function describeRange(range: PriceRange): string | null {
  if (isUnbounded(range)) return null;
  if (range.min === null) return `Under ${money(range.max!)}`;
  if (range.max === null) return `${money(range.min)} & up`;
  return `${money(range.min)} – ${money(range.max)}`;
}
