// AUTO-GENERATED by gen_manifest.js — list of every Stitch screen in /public/design.
export type Screen = {
  slug: string;
  title: string;
  platform: "Desktop" | "Mobile";
  variant: string;
  group: string;
  hasThumb: boolean;
};

export const screens: Screen[] = [
  {
    "slug": "homepage-desktop",
    "title": "Homepage",
    "platform": "Desktop",
    "variant": "",
    "group": "Homepage",
    "hasThumb": true
  },
  {
    "slug": "homepage-desktop-high-conversion",
    "title": "Homepage",
    "platform": "Desktop",
    "variant": "High Conversion",
    "group": "Homepage",
    "hasThumb": true
  },
  {
    "slug": "homepage-desktop-pro-engineered-1",
    "title": "Homepage",
    "platform": "Desktop",
    "variant": "Pro Engineered 1",
    "group": "Homepage",
    "hasThumb": true
  },
  {
    "slug": "homepage-desktop-pro-engineered-2",
    "title": "Homepage",
    "platform": "Desktop",
    "variant": "Pro Engineered 2",
    "group": "Homepage",
    "hasThumb": false
  },
  {
    "slug": "homepage-desktop-v2",
    "title": "Homepage",
    "platform": "Desktop",
    "variant": "v2",
    "group": "Homepage",
    "hasThumb": true
  },
  {
    "slug": "homepage-mobile",
    "title": "Homepage",
    "platform": "Mobile",
    "variant": "",
    "group": "Homepage",
    "hasThumb": true
  },
  {
    "slug": "homepage-mobile-high-conversion",
    "title": "Homepage",
    "platform": "Mobile",
    "variant": "High Conversion",
    "group": "Homepage",
    "hasThumb": true
  },
  {
    "slug": "homepage-mobile-pro-engineered",
    "title": "Homepage",
    "platform": "Mobile",
    "variant": "Pro Engineered",
    "group": "Homepage",
    "hasThumb": true
  },
  {
    "slug": "homepage-mobile-v2",
    "title": "Homepage",
    "platform": "Mobile",
    "variant": "v2",
    "group": "Homepage",
    "hasThumb": true
  },
  {
    "slug": "shop-all-trikes-desktop",
    "title": "Shop All Trikes",
    "platform": "Desktop",
    "variant": "",
    "group": "Shop — All Trikes",
    "hasThumb": true
  },
  {
    "slug": "shop-all-trikes-desktop-v2",
    "title": "Shop All Trikes",
    "platform": "Desktop",
    "variant": "v2",
    "group": "Shop — All Trikes",
    "hasThumb": true
  },
  {
    "slug": "shop-all-trikes-mobile",
    "title": "Shop All Trikes",
    "platform": "Mobile",
    "variant": "",
    "group": "Shop — All Trikes",
    "hasThumb": true
  },
  {
    "slug": "electric-drift-trikes-desktop",
    "title": "Electric Drift Trikes",
    "platform": "Desktop",
    "variant": "",
    "group": "Electric Drift Trikes",
    "hasThumb": true
  },
  {
    "slug": "electric-drift-trikes-mobile",
    "title": "Electric Drift Trikes",
    "platform": "Mobile",
    "variant": "",
    "group": "Electric Drift Trikes",
    "hasThumb": true
  },
  {
    "slug": "volt-s1-pro-technical-pdp-desktop",
    "title": "Volt S1 Pro Technical Pdp",
    "platform": "Desktop",
    "variant": "",
    "group": "Product — Volt S1 Pro",
    "hasThumb": true
  },
  {
    "slug": "volt-s1-pro-technical-pdp-desktop-v2",
    "title": "Volt S1 Pro Technical Pdp",
    "platform": "Desktop",
    "variant": "v2",
    "group": "Product — Volt S1 Pro",
    "hasThumb": true
  },
  {
    "slug": "volt-s1-pro-technical-pdp-mobile",
    "title": "Volt S1 Pro Technical Pdp",
    "platform": "Mobile",
    "variant": "",
    "group": "Product — Volt S1 Pro",
    "hasThumb": true
  },
  {
    "slug": "full-cart-page-desktop",
    "title": "Full Cart Page",
    "platform": "Desktop",
    "variant": "",
    "group": "Cart",
    "hasThumb": true
  },
  {
    "slug": "the-garage-manifest-full-cart-desktop",
    "title": "Garage Manifest Full Cart",
    "platform": "Desktop",
    "variant": "",
    "group": "Cart",
    "hasThumb": true
  },
  {
    "slug": "mini-cart-mobile",
    "title": "Mini Cart",
    "platform": "Mobile",
    "variant": "",
    "group": "Cart",
    "hasThumb": true
  },
  {
    "slug": "checkout-global-desktop",
    "title": "Checkout Global",
    "platform": "Desktop",
    "variant": "",
    "group": "Checkout",
    "hasThumb": true
  },
  {
    "slug": "checkout-global-mobile",
    "title": "Checkout Global",
    "platform": "Mobile",
    "variant": "",
    "group": "Checkout",
    "hasThumb": true
  },
  {
    "slug": "order-confirmation-desktop",
    "title": "Order Confirmation",
    "platform": "Desktop",
    "variant": "",
    "group": "Order Confirmation",
    "hasThumb": true
  },
  {
    "slug": "order-confirmation-mobile",
    "title": "Order Confirmation",
    "platform": "Mobile",
    "variant": "",
    "group": "Order Confirmation",
    "hasThumb": true
  },
  {
    "slug": "search-no-results-desktop",
    "title": "Search No Results",
    "platform": "Desktop",
    "variant": "",
    "group": "Search",
    "hasThumb": true
  },
  {
    "slug": "search-results-desktop",
    "title": "Search Results",
    "platform": "Desktop",
    "variant": "",
    "group": "Search",
    "hasThumb": true
  },
  {
    "slug": "search-results-mobile",
    "title": "Search Results",
    "platform": "Mobile",
    "variant": "",
    "group": "Search",
    "hasThumb": true
  },
  {
    "slug": "rider-authentication-desktop",
    "title": "Rider Authentication",
    "platform": "Desktop",
    "variant": "",
    "group": "Account & Auth",
    "hasThumb": true
  },
  {
    "slug": "rider-dashboard-desktop",
    "title": "Rider Dashboard",
    "platform": "Desktop",
    "variant": "",
    "group": "Account & Auth",
    "hasThumb": true
  },
  {
    "slug": "rider-dashboard-mobile",
    "title": "Rider Dashboard",
    "platform": "Mobile",
    "variant": "",
    "group": "Account & Auth",
    "hasThumb": true
  },
  {
    "slug": "diy-guide-sleeve-fitting-article-desktop",
    "title": "Diy Guide Sleeve Fitting Article",
    "platform": "Desktop",
    "variant": "",
    "group": "The Tech Lab",
    "hasThumb": true
  },
  {
    "slug": "the-tech-lab-content-hub-desktop",
    "title": "Tech Lab Content Hub",
    "platform": "Desktop",
    "variant": "",
    "group": "The Tech Lab",
    "hasThumb": true
  },
  {
    "slug": "diy-guide-sleeve-fitting-article-mobile",
    "title": "Diy Guide Sleeve Fitting Article",
    "platform": "Mobile",
    "variant": "",
    "group": "The Tech Lab",
    "hasThumb": true
  },
  {
    "slug": "the-tech-lab-content-hub-mobile",
    "title": "Tech Lab Content Hub",
    "platform": "Mobile",
    "variant": "",
    "group": "The Tech Lab",
    "hasThumb": true
  },
  {
    "slug": "our-story-e-drift-trikes-desktop",
    "title": "Our Story",
    "platform": "Desktop",
    "variant": "",
    "group": "Our Story",
    "hasThumb": true
  },
  {
    "slug": "our-story-mobile",
    "title": "Our Story",
    "platform": "Mobile",
    "variant": "",
    "group": "Our Story",
    "hasThumb": true
  },
  {
    "slug": "support-hub-e-drift-trikes-desktop",
    "title": "Support Hub",
    "platform": "Desktop",
    "variant": "",
    "group": "Support",
    "hasThumb": true
  },
  {
    "slug": "support-hub-mobile",
    "title": "Support Hub",
    "platform": "Mobile",
    "variant": "",
    "group": "Support",
    "hasThumb": true
  },
  {
    "slug": "shipping-warranty-e-drift-trikes-desktop",
    "title": "Shipping Warranty",
    "platform": "Desktop",
    "variant": "",
    "group": "Shipping & Warranty",
    "hasThumb": true
  },
  {
    "slug": "your-parts-bin-wishlist-desktop",
    "title": "Your Parts Bin Wishlist",
    "platform": "Desktop",
    "variant": "",
    "group": "Wishlist",
    "hasThumb": true
  },
  {
    "slug": "404-error-off-track-desktop",
    "title": "404 Off Track",
    "platform": "Desktop",
    "variant": "",
    "group": "404",
    "hasThumb": true
  }
];

export const groups: string[] = [
  "Homepage",
  "Shop — All Trikes",
  "Electric Drift Trikes",
  "Product — Volt S1 Pro",
  "Cart",
  "Checkout",
  "Order Confirmation",
  "Search",
  "Account & Auth",
  "The Tech Lab",
  "Our Story",
  "Support",
  "Shipping & Warranty",
  "Wishlist",
  "404"
];
